use std::str::FromStr;

use crate::traits::ReadWrite;

pub enum Flags6502
{
    C = (1 << 0), // Carry Bit
    Z = (1 << 1), // Zero
    I = (1 << 2), // Disable Interrupts
    D = (1 << 3), // Decimal Mode (unused)
    B = (1 << 4), // Break
    U = (1 << 5), // Unused
    V = (1 << 6), // Overflow
    N = (1 << 7), // Negative
}

struct Instruction<'a>
{
    name: String,
    op: fn(&'a mut CPU6502<'a>) -> u8,
    addr_mode: fn(&'a mut CPU6502<'a>) -> u8,
    cycles: u8
}

pub struct CPU6502<'a>
{
    bus: &'a mut dyn ReadWrite,
    a: u8,
    x: u8,
    y: u8,
    stkp: u8,
    pc: u16,
    status: u8,
    fetched_data: u8,
    addr_abs: u16,
    addr_rel: u16,
    opcode: u8,
    cycles: u8,
    ins: [Instruction<'a>; 256]
}

impl<'a> CPU6502<'a>
{
    const STACK_START_ADDRESS: u16 = 0x1000;

    pub fn new(bus: &'a mut dyn ReadWrite) -> Self
    {
        let cpu = CPU6502
        {
            bus: bus,
            a: 0x00,
            x: 0x00,
            y: 0x00,
            stkp: 0x00,
            pc: 0x0000,
            status: 0x00,
            fetched_data: 0x00,
            addr_abs: 0x0000,
            addr_rel: 0x0000,
            opcode: 0x00,
            cycles: 0x00,
            ins: [
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},
                // Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7}, Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7},

                Instruction { name: String::from("BRK"), op: CPU6502::BRK, addr_mode: CPU6502::IMM, cycles: 7 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("ASL"), op: CPU6502::ASL, addr_mode: CPU6502::ZP0, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("PHP"), op: CPU6502::PHP, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("ASL"), op: CPU6502::ASL, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("ASL"), op: CPU6502::ASL, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 },
                Instruction { name: String::from("BPL"), op: CPU6502::BPL, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("ASL"), op: CPU6502::ASL, addr_mode: CPU6502::ZPX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("CLC"), op: CPU6502::CLC, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("ORA"), op: CPU6502::ORA, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("ASL"), op: CPU6502::ASL, addr_mode: CPU6502::ABX, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 },
                Instruction { name: String::from("JSR"), op: CPU6502::JSR, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("BIT"), op: CPU6502::BIT, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("ROL"), op: CPU6502::ROL, addr_mode: CPU6502::ZP0, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("PLP"), op: CPU6502::PLP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("ROL"), op: CPU6502::ROL, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("BIT"), op: CPU6502::BIT, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("ROL"), op: CPU6502::ROL, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 },
                Instruction { name: String::from("BMI"), op: CPU6502::BMI, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("ROL"), op: CPU6502::ROL, addr_mode: CPU6502::ZPX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("SEC"), op: CPU6502::SEC, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("AND"), op: CPU6502::AND, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("ROL"), op: CPU6502::ROL, addr_mode: CPU6502::ABX, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 },
                Instruction { name: String::from("RTI"), op: CPU6502::RTI, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("LSR"), op: CPU6502::LSR, addr_mode: CPU6502::ZP0, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("PHA"), op: CPU6502::PHA, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("LSR"), op: CPU6502::LSR, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("JMP"), op: CPU6502::JMP, addr_mode: CPU6502::ABS, cycles: 3 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("LSR"), op: CPU6502::LSR, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 },
                Instruction { name: String::from("BVC"), op: CPU6502::BVC, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("LSR"), op: CPU6502::LSR, addr_mode: CPU6502::ZPX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("CLI"), op: CPU6502::CLI, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("EOR"), op: CPU6502::EOR, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("LSR"), op: CPU6502::LSR, addr_mode: CPU6502::ABX, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 },
                Instruction { name: String::from("RTS"), op: CPU6502::RTS, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("ROR"), op: CPU6502::ROR, addr_mode: CPU6502::ZP0, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("PLA"), op: CPU6502::PLA, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("ROR"), op: CPU6502::ROR, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("JMP"), op: CPU6502::JMP, addr_mode: CPU6502::IND, cycles: 5 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("ROR"), op: CPU6502::ROR, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 },
                Instruction { name: String::from("BVS"), op: CPU6502::BVS, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("ROR"), op: CPU6502::ROR, addr_mode: CPU6502::ZPX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("SEI"), op: CPU6502::SEI, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("ADC"), op: CPU6502::ADC, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("ROR"), op: CPU6502::ROR, addr_mode: CPU6502::ABX, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 },
                Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("STY"), op: CPU6502::STY, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("STX"), op: CPU6502::STX, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("DEY"), op: CPU6502::DEY, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("TXA"), op: CPU6502::TXA, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("STY"), op: CPU6502::STY, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("STX"), op: CPU6502::STX, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 4 },
                Instruction { name: String::from("BCC"), op: CPU6502::BCC, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::IZY, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("STY"), op: CPU6502::STY, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("STX"), op: CPU6502::STX, addr_mode: CPU6502::ZPY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("TYA"), op: CPU6502::TYA, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::ABY, cycles: 5 }, Instruction { name: String::from("TXS"), op: CPU6502::TXS, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("STA"), op: CPU6502::STA, addr_mode: CPU6502::ABX, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 },
                Instruction { name: String::from("LDY"), op: CPU6502::LDY, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("LDX"), op: CPU6502::LDX, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("LDY"), op: CPU6502::LDY, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("LDX"), op: CPU6502::LDX, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 3 }, Instruction { name: String::from("TAY"), op: CPU6502::TAY, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("TAX"), op: CPU6502::TAX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("LDY"), op: CPU6502::LDY, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("LDX"), op: CPU6502::LDX, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 4 },
                Instruction { name: String::from("BCS"), op: CPU6502::BCS, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("LDY"), op: CPU6502::LDY, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("LDX"), op: CPU6502::LDX, addr_mode: CPU6502::ZPY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("CLV"), op: CPU6502::CLV, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("TSX"), op: CPU6502::TSX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("LDY"), op: CPU6502::LDY, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("LDA"), op: CPU6502::LDA, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("LDX"), op: CPU6502::LDX, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 4 },
                Instruction { name: String::from("CPY"), op: CPU6502::CPY, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("CPY"), op: CPU6502::CPY, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("DEC"), op: CPU6502::DEC, addr_mode: CPU6502::ZP0, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("INY"), op: CPU6502::INY, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("DEX"), op: CPU6502::DEX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("CPY"), op: CPU6502::CPY, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("DEC"), op: CPU6502::DEC, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 },
                Instruction { name: String::from("BNE"), op: CPU6502::BNE, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("DEC"), op: CPU6502::DEC, addr_mode: CPU6502::ZPX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("CLD"), op: CPU6502::CLD, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("NOP"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("CMP"), op: CPU6502::CMP, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("DEC"), op: CPU6502::DEC, addr_mode: CPU6502::ABX, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 },
                Instruction { name: String::from("CPX"), op: CPU6502::CPX, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::IZX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("CPX"), op: CPU6502::CPX, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::ZP0, cycles: 3 }, Instruction { name: String::from("INC"), op: CPU6502::INC, addr_mode: CPU6502::ZP0, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 5 }, Instruction { name: String::from("INX"), op: CPU6502::INX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::IMM, cycles: 2 }, Instruction { name: String::from("NOP"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::SBC, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("CPX"), op: CPU6502::CPX, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::ABS, cycles: 4 }, Instruction { name: String::from("INC"), op: CPU6502::INC, addr_mode: CPU6502::ABS, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 },
                Instruction { name: String::from("BEQ"), op: CPU6502::BEQ, addr_mode: CPU6502::REL, cycles: 2 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::IZY, cycles: 5 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 8 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::ZPX, cycles: 4 }, Instruction { name: String::from("INC"), op: CPU6502::INC, addr_mode: CPU6502::ZPX, cycles: 6 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 6 }, Instruction { name: String::from("SED"), op: CPU6502::SED, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::ABY, cycles: 4 }, Instruction { name: String::from("NOP"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 2 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::NOP, addr_mode: CPU6502::IMP, cycles: 4 }, Instruction { name: String::from("SBC"), op: CPU6502::SBC, addr_mode: CPU6502::ABX, cycles: 4 }, Instruction { name: String::from("INC"), op: CPU6502::INC, addr_mode: CPU6502::ABX, cycles: 7 }, Instruction { name: String::from("???"), op: CPU6502::XXX, addr_mode: CPU6502::IMP, cycles: 7 },
            ]
        };

        return cpu;
    }

    pub fn get_flag(&self, f: Flags6502) -> u8
    {
        return self.status & (1 << (f as u8));
    }

    pub fn set_flag(&mut self, f: Flags6502, b: bool)
    {
        self.status = self.status | ((b as u8) << (f as u8));
    }

    // #region Addressing Modes
    pub fn IMP(&'a mut self) -> u8 { return 0; }
    pub fn IMM(&'a mut self) -> u8 { return 0; }
    pub fn ZP0(&'a mut self) -> u8 { return 0; }
    pub fn ZPX(&'a mut self) -> u8 { return 0; }
    pub fn ZPY(&'a mut self) -> u8 { return 0; }
    pub fn REL(&'a mut self) -> u8 { return 0; }
    pub fn ABS(&'a mut self) -> u8 { return 0; }
    pub fn ABX(&'a mut self) -> u8 { return 0; }
    pub fn ABY(&'a mut self) -> u8 { return 0; }
    pub fn IND(&'a mut self) -> u8 { return 0; }
    pub fn IZX(&'a mut self) -> u8 { return 0; }
    pub fn IZY(&'a mut self) -> u8 { return 0; }

    // Opcodes
    pub fn ADC(&'a mut self) -> u8 { return 0; }
    pub fn AND(&'a mut self) -> u8 { return 0; }
    pub fn ASL(&'a mut self) -> u8 { return 0; }
    pub fn BCC(&'a mut self) -> u8 { return 0; }
    pub fn BCS(&'a mut self) -> u8 { return 0; }
    pub fn BEQ(&'a mut self) -> u8 { return 0; }
    pub fn BIT(&'a mut self) -> u8 { return 0; }
    pub fn BMI(&'a mut self) -> u8 { return 0; }
    pub fn BNE(&'a mut self) -> u8 { return 0; }
    pub fn BPL(&'a mut self) -> u8 { return 0; }
    pub fn BRK(&'a mut self) -> u8 { return 0; }
    pub fn BVC(&'a mut self) -> u8 { return 0; }
    pub fn BVS(&'a mut self) -> u8 { return 0; }
    pub fn CLC(&'a mut self) -> u8 { return 0; }
    pub fn CLD(&'a mut self) -> u8 { return 0; }
    pub fn CLI(&'a mut self) -> u8 { return 0; }
    pub fn CLV(&'a mut self) -> u8 { return 0; }
    pub fn CMP(&'a mut self) -> u8 { return 0; }
    pub fn CPX(&'a mut self) -> u8 { return 0; }
    pub fn CPY(&'a mut self) -> u8 { return 0; }
    pub fn DEC(&'a mut self) -> u8 { return 0; }
    pub fn DEX(&'a mut self) -> u8 { return 0; }
    pub fn DEY(&'a mut self) -> u8 { return 0; }
    pub fn EOR(&'a mut self) -> u8 { return 0; }
    pub fn INC(&'a mut self) -> u8 { return 0; }
    pub fn INX(&'a mut self) -> u8 { return 0; }
    pub fn INY(&'a mut self) -> u8 { return 0; }
    pub fn JMP(&'a mut self) -> u8 { return 0; }
    pub fn JSR(&'a mut self) -> u8 { return 0; }
    pub fn LDA(&'a mut self) -> u8 { return 0; }
    pub fn LDX(&'a mut self) -> u8 { return 0; }
    pub fn LDY(&'a mut self) -> u8 { return 0; }
    pub fn LSR(&'a mut self) -> u8 { return 0; }
    pub fn NOP(&'a mut self) -> u8 { return 0; }
    pub fn ORA(&'a mut self) -> u8 { return 0; }
    pub fn PHA(&'a mut self) -> u8 { return 0; }
    pub fn PHP(&'a mut self) -> u8 { return 0; }
    pub fn PLA(&'a mut self) -> u8 { return 0; }
    pub fn PLP(&'a mut self) -> u8 { return 0; }
    pub fn ROL(&'a mut self) -> u8 { return 0; }
    pub fn ROR(&'a mut self) -> u8 { return 0; }
    pub fn RTI(&'a mut self) -> u8 { return 0; }
    pub fn RTS(&'a mut self) -> u8 { return 0; }
    pub fn SBC(&'a mut self) -> u8 { return 0; }
    pub fn SEC(&'a mut self) -> u8 { return 0; }
    pub fn SED(&'a mut self) -> u8 { return 0; }
    pub fn SEI(&'a mut self) -> u8 { return 0; }
    pub fn STA(&'a mut self) -> u8 { return 0; }
    pub fn STX(&'a mut self) -> u8 { return 0; }
    pub fn STY(&'a mut self) -> u8 { return 0; }
    pub fn TAX(&'a mut self) -> u8 { return 0; }
    pub fn TAY(&'a mut self) -> u8 { return 0; }
    pub fn TSX(&'a mut self) -> u8 { return 0; }
    pub fn TXA(&'a mut self) -> u8 { return 0; }
    pub fn TXS(&'a mut self) -> u8 { return 0; }
    pub fn TYA(&'a mut self) -> u8 { return 0; }

    
    pub fn XXX(&'a mut self) -> u8 { return 0; }

    // Other signals
    pub fn clock_tick(&'a mut self)
    {
        if(self.cycles == 0)
        {
            self.opcode = self.read(self.pc);
            self.pc += 1;

            self.cycles = self.ins[self.opcode as usize].cycles;
            (self.ins[self.opcode as usize].addr_mode)(self);
            (self.ins[self.opcode as usize].op)(self);
        }
    }

    pub fn reset(&mut self) {}
    pub fn irq(&mut self) {}
    pub fn nmi(&mut self) {}

    // Helpers
    pub fn fetch() {}

}

impl<'a> ReadWrite for CPU6502<'a>
{
    fn write(&mut self, address: u16, data: u8)
    {
        self.bus.write(address, data);
    }

    fn read(&self, address: u16) -> u8
    {
        return self.bus.read(address);
    }
}